### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by wjthomas9** [devoptix/gulp-nunjucks-api#1]
Is there any way to catch an error and prevent it from stopping gulp? It seems like gulp-nunjucks-html has something. Would this require something similar?

https://github.com/giaman/gulp-nunjucks-html

**Comment by waynebloss** [comment]
Thanks for this suggestion. I will add a configuration option for this feature as soon as possible.

If you want to fix it in your own project for now, just open up your `node_modules/gulp-nunjucks-api/index.js` file and comment out [this line](https://github.com/devoptix/gulp-nunjucks-api/blob/master/index.js#L163) where it says `_this.emit('error', createError(err));` or change it to a console.log statement. (At least, I think that should do it.)

**Comment by wjthomas9** [comment]
Ok. I'll give that a shot. Thanks!

**Comment by waynebloss** [comment]
I added a new config option called `errors` in v0.6.2 and updated the readme with the following:

- **errors** _(default: true)_ Boolean. Whether to emit errors to gulp or not.
Set to `false` to let the gulp task continue on errors. See also: the verbose
option.

The readme also now also includes info about an option called `verbose`.

So, for your case you would want to set `errors: false`. Then it will not emit an error to gulp, which is how `gulp-nunjucks-html` seems to work. I hope that solves your use case. If not I'll have to get some more details about the types of errors you're dealing with and I'll leave the issue open for now.

**Comment by waynebloss** [comment]
Feel free to close this issue if the change fixes it for you. Thanks.

**Comment by wjthomas9** [comment]
The error seems to be triggered gulp-data iterating over the src files and trying to find a matching json file for each one. So, maybe I need to look into a way to handle gulp-data errors.

Here's my task:

```
function getDataForFile(file){
    // return require('./build/data/' + path.basename(file.path, '.html') + '.json'); //require caches the file so requires gulp stop/start

    //JSON.parse does not require gulp stop/start
    return JSON.parse(fs.readFileSync('./build/data/' + path.basename(file.path, '.html') + '.json'));
}


//Compile HTML Templates
gulp.task('templates', ['host'], function() {
    return gulp.src(src.templateFiles)
        .pipe(data(getDataForFile))
        .on('error', function(err) {
            // console.log(err.message); //don't output error for now
            this.emit('end');
        })
        .pipe(nunjucksRender({
            src: [src.html, src.html + "/templates", src.html + "/layouts", src.html + "/partials"],
            errors: false
        }))
        .pipe(prettify({
            indent_size: 4,
            indent_with_tabs: true,
            preserve_newlines: true
        }))
        .pipe(gulp.dest(dist.prototypeDir));
});
```

**Comment by waynebloss** [comment]
OK, so try doing something like this:

```javascript
function getDataForFile(file){
  try {
    return JSON.parse(fs.readFileSync('./build/data/' + path.basename(file.path, '.html') + '.json'));
  } catch(err) {
    // Do something with the error here if you want like: console.log('Error: ' + err);
  }
  return {}; // Just return a blank object as the default data for the requested file.
}
```

**Comment by wjthomas9** [comment]
Awesome! That works great.
