### ISSUE TITLE
TypeError with array or `src` globs since v0.6.4

### ISSUE THREAD

**Issue by axelboc** [devoptix/gulp-nunjucks-api#3]
In version 0.6.4, I get the following error: `TypeError: Arguments to path.resolve must be strings` at `configureFiles (index.js:58:27)`.

I believe it's because I set `src` to be an array of globs:
```
src: [
	'core/templates',
	'theme/templates'
]
```

It was working fine in version 0.6.1, so I assume the responsible commit is 806b34a0ae9472be312e2a6403a3346cdab50df7.

**Comment by waynebloss** [comment]
Whoops! Sorry about that. I'll fix it as soon as possible.

**Comment by waynebloss** [comment]
OK, I reverted the changes made in v0.6.4 in order to produce v0.6.5. So, it should be fixed now.

I didn't get around to adding tests for every scenario, so that's why that happened.

**Comment by axelboc** [comment]
No worries, thanks for the quick turnaround! :+1:
