### ISSUE TITLE
Data not available globally in template

### ISSUE THREAD

**Issue by jcarpe** [devoptix/gulp-nunjucks-api#6]
I am setting data in my gulp task however the data does not appear to be available in my template. I have the following:

```
return gulp.src( temp_pth+'pages/index.nunjucks' )
		.pipe( nunjucksRender({
			data: { version: '0.0.0' },
			src: [ 
				path.join( __dirname, '..', temp_pth, 'pages' ),
				path.join( __dirname, '..', temp_pth, 'components' )
			]
		}))
		.pipe( gulp.dest( path.join( GLOBAL.config.buildPath, 'site' ) ) )
		;
```
and
```
{{ version }}
```
The result is simply blank. Version is not available from the global context.

Node 5.3.0
npm 3.5.2
gulp-nunjucks-api 0.6.7

**Comment by waynebloss** [comment]
I haven't tested any of this under Node 5.3.0. Can you go into your `node_modules/gulp-nunjucks-api` and run `npm install` and then `npm test` and tell me if all the tests pass?

Thanks.

**Comment by waynebloss** [comment]
I just ran the tests under Node v4.2.3 and npm v2.14.7 and they work.

**Comment by jcarpe** [comment]
Installed and then went to run test and got the following error:
```
gulp-nunjucks-api % npm test

> gulp-nunjucks-api@0.6.7 test /Projects/proj/static-site/node_modules/gulp-nunjucks-api
> mocha --reporter spec

/Projects/proj/static-site/node_modules/gulp-nunjucks-api/node_modules/mocha/lib/utils.js:626
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/Projects/proj/static-site/node_modules/gulp-nunjucks-api/node_modules/mocha/lib/utils.js:626:15)
    at /Projects/proj/static-site/node_modules/gulp-nunjucks-api/node_modules/mocha/bin/_mocha:316:30
    at Array.forEach (native)
    at Object.<anonymous> (/Projects/proj/static-site/node_modules/gulp-nunjucks-api/node_modules/mocha/bin/_mocha:315:6)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
npm ERR! Test failed.  See above for more details.
```

**Comment by waynebloss** [comment]
OK, it sounds like you might be getting that error because of running the test from inside of `node_modules`. I didn't think that would be a problem.

So, to run the tests you'll have to clone this repo and run `npm install` and `npm test`. Unfortunately I don't have any time to work on Node v5 problems yet since I'm still heavily using Node v4. So, I'm sorry to have to ask you to test it like this but that's the best I can do.

If you don't find any issues when running the tests in it's own repo directory, post a link to your code and I'll be glad to take a quick look.

**Comment by waynebloss** [comment]
And of course I'll accept any pull requests that fix things for Node v5 as long as they don't break stuff for Node v4.

**Comment by jcarpe** [comment]
Well, good news, all tests passed running on Node 5.3.0. I'll dig a bit more and see if I can't figure out what's happening.

**Comment by jcarpe** [comment]
Turns out I was working in the wrong template. Sorry to waste your time. I'll be re-upping my coffee consumption at the moment...

Good news is it looks like Node 5 is all good!

**Comment by waynebloss** [comment]
Thanks! No time wasted at all - I'm glad to know that I can use this in Node 5 when the time comes and also that my little wrapper library here has been useful to some people. Cheers mate!
